### PR TITLE
Added scree plot to champ.SVD()

### PR DESCRIPTION
**Pull request by rrydbirk**
Added scree plot (elbow plot) to champ.SVD() through old svdvis package (outdated).
Added import ggplot2.
Added new variable Splot and description in champ.SVD().

### CODE REVIEW

**Comment by rrydbirk** [comment]
Also, if interested, I have scripts for Manhattan plot and Q-Q plot.

**Comment by YuanTian1991** [comment]
Hi Rasmus:

Sorry for the late reply. I was in a couple of deadlines (now finally submitted). >_<

I have checked the function, and yes I think it's a good design since if the second or third variables component's eigenvalues value is not hight, there is less worry about the batch effect on these components. One modification I want to do is join these figures side by side because many users run champ.SVD(), then directly check the result, so maybe it's a better idea to show them together. And maybe add the label of components on it.

**I will modify above two issues, then push it to upstream Bioconductor repo, along with my greatest thank to you in the vignette.**

**I think the Manhattan plot and Q-Q plot would be useful as well**. Actually recently one thing I am doing now is designing a comprehensive Quality Check tool for vast data sets in my group. (People keep arguing QC process in my group meeting ...). But since I did not use these two plots before, I better learn it first.

Again, thanks so much for your work. ^_^

Best
Yuan Tian

**Comment by rrydbirk** [comment]
Hi Yuan
I'm glad that you found my suggestion useful.
For Manhattan and Q-Q plots, I already have working code. Since they require DMP object to work (with adjPvalue = 1 to get all probes), I suggest incorporating them into champ.DMP function. I will create a new pull request for you to review.
/Rasmus

**Comment by YuanTian1991** [comment]
Good Idea, I will merge it then.

Thanks
Yuan Tian

**Pull request merged**
